# Generated by Django 4.2.8 on 2026-01-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahBookingCustomers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('umrahvisaprice', models.FloatField(db_column='umrahVisaPrice')),
                ('umrahvehicleprice', models.FloatField(db_column='umrahVehiclePrice')),
                ('nationality', models.CharField(db_comment='0=Pakistan, 1=Others', max_length=1)),
                ('transport', models.CharField(db_comment='0=No Transport, 1=Have Transport', max_length=1)),
                ('city', models.IntegerField()),
                ('adultscount', models.IntegerField(db_column='adultsCount')),
                ('childrencount', models.IntegerField(db_column='childrenCount')),
                ('infantscount', models.IntegerField(db_column='infantsCount')),
                ('totalroom', models.IntegerField(db_column='totalRoom')),
                ('totalnight', models.IntegerField(db_column='totalNight')),
                ('totalprice', models.FloatField(db_column='totalPrice')),
                ('created_by', models.BigIntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('customerid', models.ForeignKey(db_column='customerId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.customers')),
            ],
            options={
                'db_table': 'umrah_booking_customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UmrahBookingHotelRoom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('umrahbookingid', models.BigIntegerField(db_column='umrahBookingId')),
                ('hotelroompriceid', models.BigIntegerField(db_column='hotelRoomPriceId')),
                ('totalhotelperroom', models.IntegerField(db_column='totalhotelPerRoom')),
                ('hotelperroomtype', models.CharField(db_column='hotelPerRoomType', max_length=6)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'umrah_booking_hotel_room',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UmrahHotelRoomPeriods',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hotelid', models.PositiveBigIntegerField(db_column='hotelId')),
                ('periodfrom', models.DateField(db_column='periodFrom')),
                ('periodto', models.DateField(db_column='periodTo')),
                ('ashratype', models.CharField(db_column='ashraType', max_length=1)),
                ('periodstatus', models.CharField(db_column='periodStatus', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'umrah_hotel_room_periods',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UmrahHotelRoomPrices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodid', models.PositiveBigIntegerField(db_column='periodId')),
                ('ondayprice', models.FloatField(db_column='onDayPrice')),
                ('ondaymarkup', models.FloatField(db_column='onDayMarkup')),
                ('offdayprice', models.FloatField(db_column='offDayPrice')),
                ('offdaymarkup', models.FloatField(db_column='offDayMarkup')),
                ('roomtype', models.CharField(db_column='roomType', max_length=6)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'umrah_hotel_room_prices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UmrahHotels',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('postbyid', models.PositiveBigIntegerField(db_column='postById')),
                ('hotelname', models.CharField(db_column='hotelName', max_length=255)),
                ('vendorname', models.CharField(db_column='vendorName', max_length=255)),
                ('hotellocation', models.CharField(db_column='hotelLocation', max_length=7)),
                ('hoteldistance', models.CharField(db_column='hotelDistance', max_length=25)),
                ('basistype', models.CharField(db_column='basisType', max_length=2)),
                ('hoteltype', models.CharField(db_column='hotelType', max_length=1)),
                ('hoteldesc', models.CharField(db_column='hotelDesc', max_length=1000)),
                ('markup', models.CharField(max_length=25)),
                ('hotelstatus', models.CharField(db_column='hotelStatus', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'umrah_hotels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UmrahTransportSectors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sectorname', models.CharField(db_column='sectorName', max_length=255)),
                ('sectormarkup', models.CharField(db_column='sectorMarkup', max_length=255)),
                ('sectorstatus', models.CharField(db_column='sectorStatus', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'umrah_transport_sectors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UmrahVehiclePrices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicleid', models.PositiveBigIntegerField(db_column='vehicleId')),
                ('sectorid', models.PositiveBigIntegerField(db_column='sectorId')),
                ('vehicleprice', models.FloatField(db_column='vehiclePrice')),
                ('vehiclesectormarkup', models.IntegerField(db_column='vehicleSectorMarkup')),
                ('vehiclesectormrkprice', models.FloatField(db_column='vehicleSectorMrkPrice')),
                ('vehiclepricestatus', models.CharField(db_column='vehiclePriceStatus', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'umrah_vehicle_prices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UmrahVehicles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehiclename', models.CharField(db_column='vehicleName', max_length=255)),
                ('vehiclemarkup', models.CharField(db_column='vehicleMarkup', max_length=255)),
                ('vehiclestatus', models.CharField(db_column='vehicleStatus', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'umrah_vehicles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UmrahVisas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('umrahvisaname', models.CharField(db_column='umrahVisaName', max_length=255)),
                ('umrahvisaperiodfrom', models.DateField(db_column='umrahVisaPeriodFrom')),
                ('umrahvisaperiodto', models.DateField(db_column='umrahVisaPeriodTo')),
                ('umrahvisaprice', models.FloatField(db_column='umrahVisaPrice')),
                ('umrahvisanationality', models.CharField(db_column='umrahVisaNationality', max_length=8)),
                ('umrahvisapricestatus', models.CharField(db_column='umrahVisaPriceStatus', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'umrah_visas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UmrahHotelImages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hotelimage', models.CharField(blank=True, db_column='hotelImage', max_length=255, null=True)),
                ('hotelroomtype', models.CharField(db_column='hotelRoomType', max_length=6)),
                ('hotelroomimagestatus', models.CharField(db_column='hotelRoomImageStatus', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('hotelid', models.ForeignKey(db_column='hotelId', on_delete=django.db.models.deletion.DO_NOTHING, to='umrah.umrahhotels')),
            ],
            options={
                'db_table': 'umrah_hotel_images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UmrahBookings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('hotelid', models.BigIntegerField(db_column='hotelId')),
                ('checkin', models.DateField(db_column='checkIn')),
                ('checkout', models.DateField(db_column='checkOut')),
                ('doubleroom', models.IntegerField(db_column='doubleRoom')),
                ('tripleroom', models.IntegerField(db_column='tripleRoom')),
                ('quadroom', models.IntegerField(db_column='quadRoom')),
                ('quintroom', models.IntegerField(db_column='quintRoom')),
                ('hoteltotalprice', models.IntegerField(db_column='hotelTotalPrice')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('bookingcustomerid', models.ForeignKey(db_column='bookingCustomerId', on_delete=django.db.models.deletion.DO_NOTHING, to='umrah.umrahbookingcustomers')),
            ],
            options={
                'db_table': 'umrah_bookings',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='umrahbookingcustomers',
            name='umrahsectorid',
            field=models.ForeignKey(db_column='umrahSectorId', on_delete=django.db.models.deletion.DO_NOTHING, to='umrah.umrahtransportsectors'),
        ),
        migrations.AddField(
            model_name='umrahbookingcustomers',
            name='umrahvehicleid',
            field=models.ForeignKey(db_column='umrahVehicleId', on_delete=django.db.models.deletion.DO_NOTHING, to='umrah.umrahvehicles'),
        ),
        migrations.CreateModel(
            name='TourPackages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('domestic_states_id', models.BigIntegerField(blank=True, db_comment='kpk,punjab etc', null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('tour_days', models.IntegerField(blank=True, null=True)),
                ('tour_availability', models.DateField(blank=True, db_comment='tour starting date', null=True)),
                ('price_label', models.CharField(blank=True, db_comment='0=couple, 1=per person', max_length=1, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('departure_location', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_location', models.CharField(blank=True, max_length=50, null=True)),
                ('tour_services', models.TextField(blank=True, null=True)),
                ('map', models.TextField(blank=True, null=True)),
                ('days_details', models.TextField(blank=True, null=True)),
                ('show_departure', models.CharField(blank=True, db_comment='0=hidden, 1=show', max_length=1, null=True)),
                ('fixed_date', models.CharField(blank=True, max_length=10, null=True)),
                ('tour_status', models.CharField(max_length=1)),
                ('created_by', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_by', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('cms_cp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cms.contentpages')),
            ],
            options={
                'db_table': 'tour_packages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TourImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_image', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_by', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='umrah.tourpackages')),
            ],
            options={
                'db_table': 'tour_images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CmsVisaPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryname', models.CharField(db_column='countryName', max_length=255)),
                ('packageurl', models.CharField(blank=True, db_column='packageUrl', max_length=255, null=True)),
                ('toururl', models.CharField(blank=True, db_column='tourUrl', max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('cmscontentid', models.ForeignKey(db_column='cmsContentId', on_delete=django.db.models.deletion.DO_NOTHING, to='cms.contentpages')),
            ],
            options={
                'db_table': 'cms_visa_packages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CmsVisaDurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visatitle', models.CharField(db_column='visaTitle', max_length=255)),
                ('visaprice', models.CharField(db_column='visaPrice', max_length=45)),
                ('currency', models.CharField(max_length=5)),
                ('numentries', models.CharField(db_column='numEntries', max_length=25)),
                ('duration', models.CharField(max_length=45)),
                ('validity', models.CharField(max_length=45)),
                ('validforcityid', models.CharField(db_column='validForCityId', max_length=45)),
                ('visatype', models.CharField(db_column='visaType', max_length=20)),
                ('visaincludes', models.TextField(db_column='visaIncludes')),
                ('durationstatus', models.IntegerField(db_column='durationStatus')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('visaid', models.ForeignKey(db_column='visaId', on_delete=django.db.models.deletion.DO_NOTHING, to='umrah.cmsvisapackages')),
            ],
            options={
                'db_table': 'cms_visa_durations',
                'managed': True,
            },
        ),
    ]
