# Generated by Django 4.2.8 on 2026-01-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignCallRecordingFollowups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('followupid', models.BigIntegerField(db_column='followupId')),
                ('callrecordingid', models.BigIntegerField(db_column='callRecordingId')),
                ('statustype', models.CharField(db_column='statusType', max_length=9)),
                ('reasontype', models.CharField(blank=True, db_column='reasonType', max_length=15, null=True)),
                ('callrecordingtype', models.CharField(db_column='callRecordingType', max_length=6)),
                ('details', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assign_call_recording_followups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CallRecordings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calldate', models.DateTimeField()),
                ('owner', models.CharField(max_length=20)),
                ('uuid', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=10)),
                ('zulu_type', models.CharField(blank=True, max_length=50, null=True)),
                ('exttocall', models.CharField(blank=True, max_length=20, null=True)),
                ('cnam', models.CharField(blank=True, max_length=20, null=True)),
                ('cnum', models.CharField(blank=True, max_length=20, null=True)),
                ('voicemailfile', models.CharField(blank=True, max_length=255, null=True)),
                ('recordingfile', models.CharField(blank=True, max_length=255, null=True)),
                ('callrecordingtype', models.CharField(db_column='callRecordingType', max_length=6)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'call_recordings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CmsFaqs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contentpageid', models.IntegerField(db_column='contentPageId')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('faqstatus', models.CharField(db_column='faqStatus', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cms_faqs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Followups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branchid', models.BigIntegerField(db_column='branchId')),
                ('customerid', models.BigIntegerField(db_column='customerId')),
                ('userid', models.BigIntegerField(db_column='userId')),
                ('title', models.CharField(max_length=255)),
                ('prioritytype', models.CharField(db_column='priorityType', max_length=6)),
                ('statustype', models.CharField(db_column='statusType', max_length=9)),
                ('moduletype', models.CharField(db_column='moduleType', max_length=19)),
                ('reasontype', models.CharField(blank=True, db_column='reasonType', max_length=15, null=True)),
                ('sourcetype', models.CharField(db_column='sourceType', max_length=14)),
                ('replyinminutes', models.CharField(blank=True, db_column='replyInMinutes', max_length=25, null=True)),
                ('estimatedreplytime', models.DateTimeField(blank=True, db_column='estimatedReplyTime', null=True)),
                ('lastcallstatus', models.CharField(db_column='lastCallStatus', max_length=15)),
                ('callrecordingtype', models.CharField(blank=True, db_column='callRecordingType', max_length=6, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'followups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FollowupUserLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userid', models.BigIntegerField(db_column='userId')),
                ('followupid', models.BigIntegerField(db_column='followupId')),
                ('activity', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'followup_user_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ParentPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('parenturl', models.CharField(db_column='parentUrl', max_length=100)),
                ('squanceorder', models.IntegerField(db_column='squanceOrder')),
                ('status', models.CharField(max_length=1)),
                ('pagetype', models.CharField(db_column='pageType', max_length=1)),
                ('activeid', models.IntegerField(db_column='activeId')),
                ('activetype', models.CharField(db_column='activeType', max_length=20)),
                ('websitetype', models.CharField(db_column='websiteType', max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parent_pages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContentPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatitle', models.CharField(db_column='metaTitle', max_length=100)),
                ('metadescription', models.TextField(db_column='metaDescription')),
                ('canonicalurl', models.CharField(blank=True, db_column='canonicalUrl', max_length=100, null=True)),
                ('urllink', models.CharField(db_column='urlLink', max_length=100)),
                ('packagetitle', models.CharField(db_column='packageTitle', max_length=50)),
                ('bannerimage', models.CharField(blank=True, db_column='bannerImage', max_length=255, null=True)),
                ('cardimage', models.CharField(blank=True, db_column='cardImage', max_length=255, null=True)),
                ('categories', models.CharField(blank=True, max_length=50, null=True)),
                ('currencytype', models.CharField(db_column='currencyType', max_length=5)),
                ('price', models.CharField(max_length=20)),
                ('sequence', models.IntegerField()),
                ('shortdescription', models.TextField(blank=True, db_column='shortDescription', null=True)),
                ('includes', models.TextField(blank=True, null=True)),
                ('excludes', models.TextField(blank=True, null=True)),
                ('documentsrequired', models.TextField(blank=True, db_column='documentsRequired', null=True)),
                ('type', models.IntegerField()),
                ('showonhome', models.IntegerField(db_column='showOnHome')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField()),
                ('activeid', models.IntegerField(blank=True, db_column='activeId', null=True)),
                ('activetype', models.CharField(blank=True, db_column='activeType', max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('parentid', models.ForeignKey(db_column='parentId', on_delete=django.db.models.deletion.DO_NOTHING, to='cms.parentpages')),
            ],
            options={
                'db_table': 'content_pages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CmsCallbackQueries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('leadfrom', models.CharField(db_column='leadFrom', max_length=1000)),
                ('sectors', models.CharField(blank=True, max_length=255, null=True)),
                ('moduleid', models.IntegerField(db_column='moduleId', db_comment='1=Home,2=Umrah,3=Flights,4=Visa,6=WorldTour,7=Franchise,9=AboutUs,10=Contactus,11=Hotels,12=PKTour,13=Airlines,14=Hajj,18=TravelAgency,19=Whatsapp')),
                ('domintl', models.CharField(blank=True, db_column='domIntl', max_length=20, null=True)),
                ('airlinecode', models.CharField(blank=True, db_column='airlineCode', max_length=5, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('clientip', models.CharField(blank=True, db_column='clientIp', db_comment='Visitor IP Address', max_length=20, null=True)),
                ('clientbrowser', models.CharField(blank=True, db_column='clientBrowser', db_comment='Visitor Browser Information', max_length=254, null=True)),
                ('clientplatform', models.CharField(blank=True, db_column='clientPlatform', db_comment='Visitor Operating System Information', max_length=254, null=True)),
                ('ismobile', models.CharField(blank=True, db_comment='1=Mobile,2=Not Mobile', max_length=1, null=True)),
                ('mobileinfo', models.CharField(blank=True, db_column='mobileInfo', db_comment='Visitor device', max_length=254, null=True)),
                ('referalurl', models.CharField(db_column='referalUrl', max_length=1000)),
                ('sourcetype', models.CharField(db_column='sourceType', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('customerid', models.ForeignKey(db_column='customerId', on_delete=django.db.models.deletion.DO_NOTHING, to='core.customers')),
            ],
            options={
                'db_table': 'cms_callback_queries',
                'managed': True,
            },
        ),
    ]
