export default [
    { fullName: "Pakistan", code: "PK" },
    { fullName: "Albania", code: "AL" },
    { fullName: "Åland Islands", code: "AX" },
    { fullName: "Algeria", code: "DZ" },
    { fullName: "American Samoa", code: "AS" },
    { fullName: "Andorra", code: "AD" },
    { fullName: "Angola", code: "AO" },
    { fullName: "Anguilla", code: "AI" },
    { fullName: "Antarctica", code: "AQ" },
    { fullName: "Antigua and Barbuda", code: "AG" },
    { fullName: "Argentina", code: "AR" },
    { fullName: "Armenia", code: "AM" },
    { fullName: "Aruba", code: "AW" },
    { fullName: "Australia", code: "AU" },
    { fullName: "Austria", code: "AT" },
    { fullName: "Azerbaijan", code: "AZ" },
    { fullName: "Bahamas (the)", code: "BS" },
    { fullName: "Bahrain", code: "BH" },
    { fullName: "Bangladesh", code: "BD" },
    { fullName: "Barbados", code: "BB" },
    { fullName: "Belarus", code: "BY" },
    { fullName: "Belgium", code: "BE" },
    { fullName: "Belize", code: "BZ" },
    { fullName: "Benin", code: "BJ" },
    { fullName: "Bermuda", code: "BM" },
    { fullName: "Bhutan", code: "BT" },
    { fullName: "Bolivia (Plurinational State of)", code: "BO" },
    { fullName: "Bonaire, Sint Eustatius and Saba", code: "BQ" },
    { fullName: "Bosnia and Herzegovina", code: "BA" },
    { fullName: "Botswana", code: "BW" },
    { fullName: "Bouvet Island", code: "BV" },
    { fullName: "Brazil", code: "BR" },
    { fullName: "British Indian Ocean Territory (the)", code: "IO" },
    { fullName: "Brunei Darussalam", code: "BN" },
    { fullName: "Bulgaria", code: "BG" },
    { fullName: "Burkina Faso", code: "BF" },
    { fullName: "Burundi", code: "BI" },
    { fullName: "Cabo Verde", code: "CV" },
    { fullName: "Cambodia", code: "KH" },
    { fullName: "Cameroon", code: "CM" },
    { fullName: "Canada", code: "CA" },
    { fullName: "Cayman Islands (the)", code: "KY" },
    { fullName: "Central African Republic (the)", code: "CF" },
    { fullName: "Chad", code: "TD" },
    { fullName: "Chile", code: "CL" },
    { fullName: "China", code: "CN" },
    { fullName: "Christmas Island", code: "CX" },
    { fullName: "Cocos (Keeling) Islands (the)", code: "CC" },
    { fullName: "Colombia", code: "CO" },
    { fullName: "Comoros (the)", code: "KM" },
    { fullName: "Congo (the Democratic Republic of the)", code: "CD" },
    { fullName: "Congo (the)", code: "CG" },
    { fullName: "Cook Islands (the)", code: "CK" },
    { fullName: "Costa Rica", code: "CR" },
    { fullName: "Croatia", code: "HR" },
    { fullName: "Cuba", code: "CU" },
    { fullName: "Curaçao", code: "CW" },
    { fullName: "Cyprus", code: "CY" },
    { fullName: "Czechia", code: "CZ" },
    { fullName: "Côte d'Ivoire", code: "CI" },
    { fullName: "Denmark", code: "DK" },
    { fullName: "Djibouti", code: "DJ" },
    { fullName: "Dominica", code: "DM" },
    { fullName: "Dominican Republic (the)", code: "DO" },
    { fullName: "Ecuador", code: "EC" },
    { fullName: "Egypt", code: "EG" },
    { fullName: "El Salvador", code: "SV" },
    { fullName: "Equatorial Guinea", code: "GQ" },
    { fullName: "Eritrea", code: "ER" },
    { fullName: "Estonia", code: "EE" },
    { fullName: "Eswatini", code: "SZ" },
    { fullName: "Ethiopia", code: "ET" },
    { fullName: "Falkland Islands (the) [Malvinas]", code: "FK" },
    { fullName: "Faroe Islands (the)", code: "FO" },
    { fullName: "Fiji", code: "FJ" },
    { fullName: "Finland", code: "FI" },
    { fullName: "France", code: "FR" },
    { fullName: "French Guiana", code: "GF" },
    { fullName: "French Polynesia", code: "PF" },
    { fullName: "French Southern Territories (the)", code: "TF" },
    { fullName: "Gabon", code: "GA" },
    { fullName: "Gambia (the)", code: "GM" },
    { fullName: "Georgia", code: "GE" },
    { fullName: "Germany", code: "DE" },
    { fullName: "Ghana", code: "GH" },
    { fullName: "Gibraltar", code: "GI" },
    { fullName: "Greece", code: "GR" },
    { fullName: "Greenland", code: "GL" },
    { fullName: "Grenada", code: "GD" },
    { fullName: "Guadeloupe", code: "GP" },
    { fullName: "Guam", code: "GU" },
    { fullName: "Guatemala", code: "GT" },
    { fullName: "Guernsey", code: "GG" },
    { fullName: "Guinea", code: "GN" },
    { fullName: "Guinea-Bissau", code: "GW" },
    { fullName: "Guyana", code: "GY" },
    { fullName: "Haiti", code: "HT" },
    { fullName: "Heard Island and McDonald Islands", code: "HM" },
    { fullName: "Holy See (the)", code: "VA" },
    { fullName: "Honduras", code: "HN" },
    { fullName: "Hong Kong", code: "HK" },
    { fullName: "Hungary", code: "HU" },
    { fullName: "Iceland", code: "IS" },
    { fullName: "India", code: "IN" },
    { fullName: "Indonesia", code: "ID" },
    { fullName: "Iran (Islamic Republic of)", code: "IR" },
    { fullName: "Iraq", code: "IQ" },
    { fullName: "Ireland", code: "IE" },
    { fullName: "Isle of Man", code: "IM" },
    { fullName: "Israel", code: "IL" },
    { fullName: "Italy", code: "IT" },
    { fullName: "Jamaica", code: "JM" },
    { fullName: "Japan", code: "JP" },
    { fullName: "Jersey", code: "JE" },
    { fullName: "Jordan", code: "JO" },
    { fullName: "Kazakhstan", code: "KZ" },
    { fullName: "Kenya", code: "KE" },
    { fullName: "Kiribati", code: "KI" },
    { fullName: "Korea (the Democratic People's Republic of)", code: "KP" },
    { fullName: "Korea (the Republic of)", code: "KR" },
    { fullName: "Kuwait", code: "KW" },
    { fullName: "Kyrgyzstan", code: "KG" },
    { fullName: "Lao People's Democratic Republic (the)", code: "LA" },
    { fullName: "Latvia", code: "LV" },
    { fullName: "Lebanon", code: "LB" },
    { fullName: "Lesotho", code: "LS" },
    { fullName: "Liberia", code: "LR" },
    { fullName: "Libya", code: "LY" },
    { fullName: "Liechtenstein", code: "LI" },
    { fullName: "Lithuania", code: "LT" },
    { fullName: "Luxembourg", code: "LU" },
    { fullName: "Macao", code: "MO" },
    { fullName: "Madagascar", code: "MG" },
    { fullName: "Malawi", code: "MW" },
    { fullName: "Malaysia", code: "MY" },
    { fullName: "Maldives", code: "MV" },
    { fullName: "Mali", code: "ML" },
    { fullName: "Malta", code: "MT" },
    { fullName: "Marshall Islands (the)", code: "MH" },
    { fullName: "Martinique", code: "MQ" },
    { fullName: "Mauritania", code: "MR" },
    { fullName: "Mauritius", code: "MU" },
    { fullName: "Mayotte", code: "YT" },
    { fullName: "Mexico", code: "MX" },
    { fullName: "Micronesia (Federated States of)", code: "FM" },
    { fullName: "Moldova (the Republic of)", code: "MD" },
    { fullName: "Monaco", code: "MC" },
    { fullName: "Mongolia", code: "MN" },
    { fullName: "Montenegro", code: "ME" },
    { fullName: "Montserrat", code: "MS" },
    { fullName: "Morocco", code: "MA" },
    { fullName: "Mozambique", code: "MZ" },
    { fullName: "Myanmar", code: "MM" },
    { fullName: "Namibia", code: "NA" },
    { fullName: "Nauru", code: "NR" },
    { fullName: "Nepal", code: "NP" },
    { fullName: "Netherlands (the)", code: "NL" },
    { fullName: "New Caledonia", code: "NC" },
    { fullName: "New Zealand", code: "NZ" },
    { fullName: "Nicaragua", code: "NI" },
    { fullName: "Niger (the)", code: "NE" },
    { fullName: "Nigeria", code: "NG" },
    { fullName: "Niue", code: "NU" },
    { fullName: "Norfolk Island", code: "NF" },
    { fullName: "Northern Mariana Islands (the)", code: "MP" },
    { fullName: "Norway", code: "NO" },
    { fullName: "Oman", code: "OM" },
    { fullName: "Palau", code: "PW" },
    { fullName: "Palestine, State of", code: "PS" },
    { fullName: "Panama", code: "PA" },
    { fullName: "Papua New Guinea", code: "PG" },
    { fullName: "Paraguay", code: "PY" },
    { fullName: "Peru", code: "PE" },
    { fullName: "Philippines (the)", code: "PH" },
    { fullName: "Pitcairn", code: "PN" },
    { fullName: "Poland", code: "PL" },
    { fullName: "Portugal", code: "PT" },
    { fullName: "Puerto Rico", code: "PR" },
    { fullName: "Qatar", code: "QA" },
    { fullName: "Republic of North Macedonia", code: "MK" },
    { fullName: "Romania", code: "RO" },
    { fullName: "Russian Federation (the)", code: "RU" },
    { fullName: "Rwanda", code: "RW" },
    { fullName: "Réunion", code: "RE" },
    { fullName: "Saint Barthélemy", code: "BL" },
    { fullName: "Saint Helena, Ascension and Tristan da Cunha", code: "SH" },
    { fullName: "Saint Kitts and Nevis", code: "KN" },
    { fullName: "Saint Lucia", code: "LC" },
    { fullName: "Saint Martin (French part)", code: "MF" },
    { fullName: "Saint Pierre and Miquelon", code: "PM" },
    { fullName: "Saint Vincent and the Grenadines", code: "VC" },
    { fullName: "Samoa", code: "WS" },
    { fullName: "San Marino", code: "SM" },
    { fullName: "Sao Tome and Principe", code: "ST" },
    { fullName: "Saudi Arabia", code: "SA" },
    { fullName: "Senegal", code: "SN" },
    { fullName: "Serbia", code: "RS" },
    { fullName: "Seychelles", code: "SC" },
    { fullName: "Sierra Leone", code: "SL" },
    { fullName: "Singapore", code: "SG" },
    { fullName: "Sint Maarten (Dutch part)", code: "SX" },
    { fullName: "Slovakia", code: "SK" },
    { fullName: "Slovenia", code: "SI" },
    { fullName: "Solomon Islands", code: "SB" },
    { fullName: "Somalia", code: "SO" },
    { fullName: "South Africa", code: "ZA" },
    { fullName: "South Georgia and the South Sandwich Islands", code: "GS" },
    { fullName: "South Sudan", code: "SS" },
    { fullName: "Spain", code: "ES" },
    { fullName: "Sri Lanka", code: "LK" },
    { fullName: "Sudan (the)", code: "SD" },
    { fullName: "SurifullName", code: "SR" },
    { fullName: "Svalbard and Jan Mayen", code: "SJ" },
    { fullName: "Sweden", code: "SE" },
    { fullName: "Switzerland", code: "CH" },
    { fullName: "Syrian Arab Republic", code: "SY" },
    { fullName: "Taiwan (Province of China)", code: "TW" },
    { fullName: "Tajikistan", code: "TJ" },
    { fullName: "Tanzania, United Republic of", code: "TZ" },
    { fullName: "Thailand", code: "TH" },
    { fullName: "Timor-Leste", code: "TL" },
    { fullName: "Togo", code: "TG" },
    { fullName: "Tokelau", code: "TK" },
    { fullName: "Tonga", code: "TO" },
    { fullName: "Trinidad and Tobago", code: "TT" },
    { fullName: "Tunisia", code: "TN" },
    { fullName: "Turkey", code: "TR" },
    { fullName: "Turkmenistan", code: "TM" },
    { fullName: "Turks and Caicos Islands (the)", code: "TC" },
    { fullName: "Tuvalu", code: "TV" },
    { fullName: "Uganda", code: "UG" },
    { fullName: "Ukraine", code: "UA" },
    { fullName: "United Arab Emirates (the)", code: "AE" },
    {
        fullName: "United Kingdom of Great Britain and Northern Ireland (the)",
        code: "GB",
    },
    { fullName: "United States Minor Outlying Islands (the)", code: "UM" },
    { fullName: "United States of America (the)", code: "US" },
    { fullName: "Uruguay", code: "UY" },
    { fullName: "Uzbekistan", code: "UZ" },
    { fullName: "Vanuatu", code: "VU" },
    { fullName: "Venezuela (Bolivarian Republic of)", code: "VE" },
    { fullName: "Viet Nam", code: "VN" },
    { fullName: "Virgin Islands (British)", code: "VG" },
    { fullName: "Virgin Islands (U.S.)", code: "VI" },
    { fullName: "Wallis and Futuna", code: "WF" },
    { fullName: "Western Sahara", code: "EH" },
    { fullName: "Yemen", code: "YE" },
    { fullName: "Zambia", code: "ZM" },
    { fullName: "Zimbabwe", code: "ZW" },
];