# Generated by Django 4.2.8 on 2026-04-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileVisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Visa type name (e.g., UAE Visa, Umrah Visa)', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Short tagline for the visa type', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed description of visa type')),
                ('thumbnail', models.ImageField(blank=True, help_text='Card image (400x300px recommended)', null=True, upload_to='visas/types/thumbnails/')),
                ('banner', models.ImageField(blank=True, help_text='Banner image (1920x400px recommended)', null=True, upload_to='visas/types/banners/')),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-3 country code (e.g., ARE, SAU)', max_length=3)),
                ('processing_time', models.CharField(blank=True, help_text='e.g., "3-5 working days"', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this visa type')),
                ('display_order', models.IntegerField(default=0, help_text='Order of display in lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile Visa Type',
                'verbose_name_plural': 'Mobile Visa Types',
                'db_table': 'mobile_visa_types',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MobileVisaVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Visa variant name (e.g., 30 Days Single Entry)', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Descriptive subtitle', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this variant')),
                ('thumbnail', models.ImageField(blank=True, help_text='Variant thumbnail image', null=True, upload_to='visas/variants/thumbnails/')),
                ('banner', models.ImageField(blank=True, help_text='Variant banner image', null=True, upload_to='visas/variants/banners/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Visa price', max_digits=10, null=True)),
                ('currency', models.CharField(default='PKR', help_text='Currency code (e.g., PKR, USD)', max_length=3)),
                ('validity', models.CharField(blank=True, help_text='Validity period (e.g., 60 days from issue)', max_length=100)),
                ('duration', models.CharField(blank=True, help_text='Stay duration (e.g., 30 days)', max_length=100)),
                ('num_entries', models.CharField(blank=True, help_text='Number of entries (e.g., Single, Double, Multiple)', max_length=50)),
                ('processing_time', models.CharField(blank=True, help_text='Processing time (overrides type-level if set)', max_length=100)),
                ('visa_category', models.CharField(blank=True, choices=[('tourist', 'Tourist'), ('business', 'Business'), ('transit', 'Transit'), ('work', 'Work'), ('student', 'Student'), ('family', 'Family/Visit'), ('religious', 'Religious (Umrah/Hajj)'), ('other', 'Other')], help_text='Category of this visa', max_length=50)),
                ('includes', models.TextField(blank=True, help_text='What is included in this package')),
                ('excludes', models.TextField(blank=True, help_text='What is excluded from this package')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this variant')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured on homepage')),
                ('display_order', models.IntegerField(default=0, help_text='Order of display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visa_type', models.ForeignKey(help_text='Parent visa type', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='mobile.mobilevisatype')),
            ],
            options={
                'verbose_name': 'Mobile Visa Variant',
                'verbose_name_plural': 'Mobile Visa Variants',
                'db_table': 'mobile_visa_variants',
                'ordering': ['visa_type', 'display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VisaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Rule/requirement name (e.g., Valid Passport Required)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the requirement')),
                ('rule_type', models.CharField(choices=[('transit', 'Transit Rule'), ('general', 'General Requirement')], default='general', help_text='Type of rule (transit vs general visa)', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class (e.g., fa-passport)', max_length=50)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Mark as mandatory requirement')),
                ('display_order', models.IntegerField(default=0, help_text='Order of display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visa_variant', models.ForeignKey(help_text='Parent visa variant', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='mobile.mobilevisavariant')),
            ],
            options={
                'verbose_name': 'Visa Rule',
                'verbose_name_plural': 'Visa Rules',
                'db_table': 'mobile_visa_rules',
                'ordering': ['visa_variant', 'display_order', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='mobilevisatype',
            index=models.Index(fields=['is_active', 'display_order'], name='mobile_visa_is_acti_be4812_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilevisatype',
            index=models.Index(fields=['country_code'], name='mobile_visa_country_d2dcb2_idx'),
        ),
        migrations.AddIndex(
            model_name='visarule',
            index=models.Index(fields=['visa_variant', 'display_order'], name='mobile_visa_visa_va_c8796e_idx'),
        ),
        migrations.AddIndex(
            model_name='visarule',
            index=models.Index(fields=['rule_type'], name='mobile_visa_rule_ty_f78c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilevisavariant',
            index=models.Index(fields=['visa_type', 'is_active', 'display_order'], name='mobile_visa_visa_ty_f5a65b_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilevisavariant',
            index=models.Index(fields=['visa_category'], name='mobile_visa_visa_ca_51cdf6_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilevisavariant',
            index=models.Index(fields=['is_featured'], name='mobile_visa_is_feat_253c31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mobilevisavariant',
            unique_together={('visa_type', 'title')},
        ),
    ]
