# Generated by Django 4.2.8 on 2026-04-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_mobilevisatype_mobilevisavariant_visarule_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mobilevisavariant',
            unique_together=set(),
        ),
    ]
