# Generated by Django 4.2.8 on 2026-04-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_remove_visa_variant_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, help_text='Package thumbnail image (recommended: 400x300px)', null=True, upload_to='packages/thumbnails/')),
                ('banner', models.ImageField(blank=True, help_text='Package banner image (recommended: 1920x400px)', null=True, upload_to='packages/banners/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or video URL for package preview', max_length=500)),
                ('package_type', models.CharField(choices=[('umrah', 'Umrah Package'), ('hajj', 'Hajj Package'), ('tour', 'Tour Package'), ('hotel', 'Hotel Package'), ('flight', 'Flight Package'), ('visa', 'Visa Package'), ('combo', 'Combo Package'), ('other', 'Other')], default='tour', help_text='Type of package', max_length=50)),
                ('title', models.CharField(help_text='Package title/name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly unique identifier', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed package description')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g., "5-star,family-friendly,budget")', max_length=500)),
                ('contact_no', models.CharField(blank=True, help_text='Contact phone number', max_length=50)),
                ('whatsapp_no', models.CharField(blank=True, help_text='WhatsApp number for inquiries', max_length=50)),
                ('informational_message', models.TextField(blank=True, help_text='Special message or note for customers')),
                ('starting_from', models.DecimalField(blank=True, decimal_places=2, help_text='Starting price (e.g., "Starting from PKR 150,000")', max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Package price', max_digits=10)),
                ('currency', models.CharField(default='PKR', help_text='Currency code (e.g., PKR, USD, SAR)', max_length=3)),
                ('location', models.CharField(blank=True, help_text='Package location/destination', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this package')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured package')),
                ('display_order', models.IntegerField(default=0, help_text='Order of display in lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile Package',
                'verbose_name_plural': 'Mobile Packages',
                'db_table': 'mobile_packages',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='mobile_pack_is_acti_962255_idx'), models.Index(fields=['package_type'], name='mobile_pack_package_946efa_idx'), models.Index(fields=['is_featured'], name='mobile_pack_is_feat_cc7764_idx'), models.Index(fields=['slug'], name='mobile_pack_slug_0f28c6_idx')],
            },
        ),
    ]
