# Generated by Django 4.2.8 on 2026-01-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentid', models.PositiveIntegerField(db_column='agentId')),
                ('parentid', models.IntegerField(db_column='parentId')),
                ('refnumber', models.CharField(db_column='refNumber', max_length=255)),
                ('depositaccount', models.CharField(db_column='depositAccount', max_length=45)),
                ('createdid', models.PositiveIntegerField(db_column='createdId')),
                ('createdtype', models.CharField(db_column='createdType', max_length=5)),
                ('createdby', models.CharField(db_column='createdBy', max_length=45)),
                ('createddatetime', models.DateTimeField(db_column='createdDateTime')),
                ('approvedid', models.PositiveIntegerField(db_column='approvedId')),
                ('approvedtype', models.CharField(db_column='approvedType', max_length=5)),
                ('approvedby', models.CharField(db_column='approvedBy', max_length=45)),
                ('approveddatetime', models.DateTimeField(blank=True, db_column='approvedDateTime', null=True)),
                ('paymenttype', models.CharField(db_column='paymentType', max_length=25)),
                ('creditlimit', models.FloatField(db_column='creditLimit')),
                ('currentcreditlimit', models.FloatField(db_column='currentCreditLimit')),
                ('depositdate', models.DateTimeField(db_column='depositDate')),
                ('depositamount', models.FloatField(db_column='depositAmount')),
                ('attachment', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=1000)),
                ('paymentstatus', models.CharField(db_column='paymentStatus', max_length=25)),
                ('transactiontype', models.CharField(db_column='transactionType', max_length=20)),
                ('scopetype', models.CharField(db_column='scopeType', max_length=25)),
                ('sourcetype', models.CharField(db_column='sourceType', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MarkupAndMarkdowns',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parentid', models.PositiveBigIntegerField(db_column='parentId')),
                ('userid', models.PositiveBigIntegerField(db_column='userId')),
                ('postbyid', models.BigIntegerField(db_column='postbyId')),
                ('postbytype', models.CharField(db_column='postbyType', max_length=5)),
                ('title', models.CharField(max_length=45)),
                ('itinerarytype', models.CharField(db_column='itineraryType', max_length=3)),
                ('faretype', models.CharField(db_column='fareType', max_length=2)),
                ('servicefeetype', models.CharField(db_column='serviceFeeType', max_length=3)),
                ('passengertype', models.CharField(db_column='passengerType', max_length=5)),
                ('servicetype', models.CharField(db_column='serviceType', max_length=5)),
                ('markuptype', models.CharField(db_column='markupType', max_length=10)),
                ('servicefee', models.FloatField(db_column='serviceFee')),
                ('airlinetype', models.CharField(blank=True, db_column='airlineType', max_length=25, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('agentid', models.ForeignKey(db_column='agentId', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.agents')),
            ],
            options={
                'db_table': 'markup_and_markdowns',
                'managed': True,
            },
        ),
    ]
