# Generated by Django 4.2.8 on 2026-01-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=25)),
                ('contactno', models.CharField(db_column='contactNo', max_length=20)),
                ('status', models.CharField(max_length=1)),
                ('ceated_at', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'administrative_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('postbyid', models.BigIntegerField(blank=True, db_column='postbyId', null=True)),
                ('postbytype', models.CharField(blank=True, db_column='postbyType', max_length=5, null=True)),
                ('bankname', models.CharField(db_column='bankName', max_length=100)),
                ('accounttitle', models.CharField(db_column='accountTitle', max_length=100)),
                ('branchcode', models.CharField(db_column='branchCode', max_length=10)),
                ('accountno', models.CharField(db_column='accountNo', max_length=25)),
                ('ibanno', models.CharField(db_column='ibanNo', max_length=50)),
                ('swiftcode', models.CharField(db_column='swiftCode', max_length=15)),
                ('contactno', models.CharField(db_column='contactNo', max_length=30)),
                ('bankstatus', models.CharField(db_column='bankStatus', max_length=1)),
                ('banklogoname', models.CharField(db_column='bankLogoName', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bank_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branchname', models.CharField(db_column='branchName', max_length=45, unique=True)),
                ('branchaddress', models.CharField(db_column='branchAddress', max_length=255)),
                ('branchphone', models.CharField(db_column='branchPhone', max_length=30)),
                ('mapaddress', models.CharField(db_column='mapAddress', max_length=500)),
                ('branchstatus', models.CharField(db_column='branchStatus', max_length=9)),
                ('branchsequance', models.IntegerField(db_column='branchSequance')),
                ('showonhome', models.CharField(db_column='showOnHome', max_length=1)),
                ('branch_type', models.CharField(blank=True, db_column='branch_Type', db_comment='1=Branch, 2=Sale Point', max_length=1, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branches',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyname', models.CharField(db_column='currencyName', max_length=50)),
                ('currencyflag', models.CharField(db_column='currencyFlag', max_length=255)),
                ('currencycode', models.CharField(db_column='currencyCode', max_length=10)),
                ('currencysymbol', models.CharField(db_collation='utf8mb3_general_ci', db_column='currencySymbol', max_length=20)),
                ('countryname', models.CharField(db_column='countryName', max_length=255)),
                ('countrycode', models.CharField(db_column='countryCode', max_length=10)),
                ('currencyrate', models.FloatField(db_column='currencyRate')),
                ('status', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'currencies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=25, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=25, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('cnicissuedate', models.DateField(blank=True, db_column='cnicIssueDate', null=True)),
                ('cnicexpirydate', models.DateField(blank=True, db_column='cnicExpiryDate', null=True)),
                ('mobileno', models.CharField(db_column='mobileNo', max_length=25)),
                ('phoneno', models.CharField(blank=True, db_column='phoneNo', max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('passportno', models.CharField(blank=True, db_column='passportNo', max_length=20, null=True)),
                ('passportissuedate', models.DateField(blank=True, db_column='passportIssueDate', null=True)),
                ('passportexpirydate', models.DateField(blank=True, db_column='passportExpiryDate', null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, db_column='createdBy', null=True)),
                ('dnd', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RestApiCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiontype', models.CharField(db_column='versionType', max_length=45)),
                ('version', models.CharField(max_length=45)),
                ('ipcc', models.CharField(db_column='Ipcc', max_length=45)),
                ('usernameorid', models.CharField(db_column='userNameOrID', max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('agentusernameorid', models.CharField(db_column='agentUserNameOrID', max_length=500)),
                ('agtpassword', models.CharField(db_column='agtPassword', max_length=500)),
                ('useridorkey', models.CharField(db_column='userIDOrKey', max_length=255)),
                ('target', models.CharField(max_length=10)),
                ('echotoken', models.CharField(db_column='echoToken', max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('bookingurl', models.CharField(db_column='bookingUrl', max_length=255)),
                ('ancillaryurl', models.CharField(db_column='ancillaryUrl', max_length=255)),
                ('partyinfo', models.TextField(db_column='partyInfo')),
                ('senderinfo', models.TextField(db_column='senderInfo')),
                ('credentialtype', models.CharField(db_column='credentialType', max_length=10)),
                ('airlinetype', models.CharField(db_column='airlineType', max_length=45)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rest_api_credentials',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('sectortype', models.CharField(db_column='sectorType', max_length=3)),
                ('allowtype', models.CharField(db_column='allowType', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sectors',
                'managed': True,
            },
        ),
    ]
